// examples/react/ParticleCanvas.tsx
import { useEffect, useRef } from 'react';

import { GritEngine } from '@nullcipherr/grit-engine';

export function ParticleCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvasRef.current) return;

    const engine = new GritEngine({
      canvas: canvasRef.current,
      seed: 42,
      executionMode: 'main-thread'
    });

    engine.start();

    return () => {
      engine.dispose();
    };
  }, []);

  return <canvas ref={canvasRef} style={{ width: '100%', height: '100%' }} />;
}

// examples/vue/ParticleCanvas.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';

import { GritEngine } from '@nullcipherr/grit-engine';

const canvasRef = ref<HTMLCanvasElement | null>(null);
let engine: GritEngine | null = null;

onMounted(() => {
  if (!canvasRef.value) return;

  engine = new GritEngine({
    canvas: canvasRef.value,
    seed: 42,
    executionMode: 'main-thread'
  });

  engine.start();
});

onBeforeUnmount(() => {
  engine?.dispose();
  engine = null;
});
</script>

<template>
  <canvas ref="canvasRef" style="width: 100%; height: 100%" />
</template>
