// examples/react/ParticleCanvas.tsx
import { useEffect, useRef } from 'react';

import { GritEngine } from '@nullcipherr/grit-engine';

export function ParticleCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvasRef.current) return;

    const engine = new GritEngine({
      canvas: canvasRef.current,
      seed: 42,
      executionMode: 'main-thread'
    });

    engine.start();

    return () => {
      engine.dispose();
    };
  }, []);

  return <canvas ref={canvasRef} style={{ width: '100%', height: '100%' }} />;
}

// examples/svelte/ParticleCanvas.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';

  import { GritEngine } from '@nullcipherr/grit-engine';

  let canvasEl: HTMLCanvasElement;
  let engine: GritEngine | null = null;

  onMount(() => {
    engine = new GritEngine({
      canvas: canvasEl,
      seed: 42,
      executionMode: 'main-thread'
    });

    engine.start();
  });

  onDestroy(() => {
    engine?.dispose();
    engine = null;
  });
</script>

<canvas bind:this={canvasEl} style="width: 100%; height: 100%" />
